config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :drawings
  resources :months
  resources :sessions
  

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

  get 'months/latest' => 'months#latest', as: :current
  root 'months#latest'

  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Dddd</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div id="leftcol" class="col-md-2">
					<h1><a href="/">Le dessin du dix du mois</a></h1>
					<ul>
						<li><a href="/months/">Tous les dix</a></li>
						<li><a href="/users/">Les dessinateurs</a></li>
						<% if current_user %>
							<li><a href="/drawings/new">Poster un dessin</a></li>
						<% end %>
					</ul>

					
				</div>
				<div id="maincontent" class="col-md-9 col-md-offset-1">
					<% if notice %>
						<div class="alert alert-success"><%= notice %></div>
					<% end %>
					<% if alert %>
						<div class="alert alert-danger"><%= alert %></div>
					<% end %>
					
					<div class="pull-right">
						<% if current_user %>
							<%= link_to 'Profil', controller: "users",
							action: "show", id: current_user[:id] %>
							<%= link_to 'Déconnexion', logout_path %>
						<% else %>
							<%= link_to 'Connexion', login_path %>
						<% end %>
					</div>
					<%= yield %>
				</div>
			</div>
		</div>
	</body>
</html>